Repository rkwhrcjsaud/ft_transcendence, pull requests merged in 2025-01, with the labels that each got.

#107 [Fix/#106] game 관련 이름(함수명,파일명) 변경, js 컬러코드 에러 수정
  front/src/app.js
  front/src/page/game.js
  front/styles/game.css
Labels: Fix

#109 [Fix/#108] 회원가입 - 유저 플로우 수정 / 이메일 인증 - 코드 수정 및 다국어 번역 수정
  front/src/auth/verifyEmail.js
  front/src/page/editProfile.js
  front/src/page/login.js
  front/src/page/register.js
  front/src/utils/language.js
  front/src/vault.js
  front/styles/register.css
Labels: Fix

#111 [Feat/#110] 페이지 이동 시 기존 HTML을 초기화하는 기능 추가
  front/src/app.js
  front/src/auth/verifyEmail.js
  front/styles/verifyEmail.css
Labels: Feat

#113 [Refactor/#112] 회원가입, 로그인 문제 해결 중 중간 저장
  Makefile
  back/transcendence/settings.py
  front/src/auth/verifyEmail.js
  front/src/page/login.js
  front/src/page/register.js
  front/src/utils/axiosInterceptor.js
  front/src/utils/language.js
  front/src/vault.js
  vault/tools/frontrole.sh
Labels: Refactor

#116 [Feat/#115] 프론트의 vault-data(role-id, secret-id) API 생성 및 vault.js에 API 연동
  back/transcendence/urls.py
  back/transcendence/views.py
  docker-compose.yaml
  front/src/vault.js
Labels: Feat

#118 [Fix/#117] 상단 네비게이션 바 로그인/로그아웃 버튼 로직 수정
  front/index.html
Labels: Fix

#120 [Feat/#114] 로그인 기능 추가
  front/src/app.js
  front/src/auth/authProvider.js
  front/src/page/login.js
  front/src/utils/axiosInterceptor.js
Labels: Feat

#123 [Fix/#122] index.html 오류 수정, 이메일 인증 페이지 전송 버튼 삭제
  front/index.html
  front/src/auth/authProvider.js
  front/src/auth/verifyEmail.js
  front/src/vault.js
  front/styles/verifyEmail.css
Labels: Fix

#125 [Fix/#121] 로컬 스토리지 조정 및 소셜로그인 기능 복구
  back/Dockerfile
  back/accounts/serializers.py
  back/social_accounts/serializers.py
  back/social_accounts/utils.py
  back/social_accounts/views.py
  back/transcendence/settings.py
  front/index.html
  front/src/auth/socialLogin.js
  vault/tools/backrole.sh
  vault/tools/setup.sh
Labels: Fix

#130 [Feat/#124] /edit_profile 페이지 API 연동(back에서 목데이터로 테스트)
  back/accounts/models.py
  back/accounts/serializers.py
  back/accounts/views.py
  back/transcendence/urls.py
  front/src/auth/authProvider.js
  front/src/page/editProfile.js
  front/src/page/login.js
  front/src/utils/language.js
  front/styles/editProfile.css
Labels: Feat

#132 [Feat/#126] 매치 히스토리 추가, 로그인 수정
  back/accounts/models.py
  back/accounts/serializers.py
  back/accounts/urls.py
  back/accounts/views.py
  back/localgame/consumers.py
  front/src/auth/authProvider.js
  front/src/page/game.js
  front/src/page/login.js
  front/src/utils/matchhistory.js
Labels: Feat

#134 [Feat/#133] 프로필 수정 페이지 기능 추가
  back/accounts/models.py
  back/accounts/serializers.py
  back/accounts/views.py
  back/localgame/consumers.py
  back/social_accounts/serializers.py
  back/social_accounts/utils.py
  front/src/auth/authProvider.js
  front/src/page/editProfile.js
  front/src/page/game.js
  vault/tools/backrole.sh
  vault/tools/setup.sh
Labels: Feat

#153 [Feat/#152] 비밀번호 변경 API 추가 및 기능 구현, 42 로그인일시 비밀번호 변경 비활성화 기능 추가
  back/accounts/managers.py
  back/accounts/migrations/0001_initial.py
  back/accounts/models.py
  back/accounts/serializers.py
  back/accounts/urls.py
  back/accounts/views.py
  front/src/page/changePassword.js
  front/src/page/dashboard_related/profileAccordion.js
  front/src/page/register.js
Labels: Feat

#154 [Feat/#142] 중간 저장
  .gitignore
  back/accounts/migrations/0001_initial.py
  back/accounts/migrations/__init__.py
  back/accounts/models.py
  back/accounts/serializers.py
  back/friends/migrations/0001_initial.py
  back/friends/migrations/__init__.py
  back/social_accounts/migrations/__init__.py
  back/social_accounts/serializers.py
  back/social_accounts/utils.py
  front/src/page/dashboard_related/friendListAccordion.js
  front/src/page/dashboard_related/profileAccordion.js
Labels: Feat

#159 [Feat/#142] 친구 목록 생성 및 조회
  back/friends/views.py
  front/src/page/dashboard_related/friendListAccordion.js
Labels: Feat

#160 [Fix/#157] 비밀번호 변경 기능 수정, editProfile.js, changePassword.js에서의 getSecretValue() 사용
  back/accounts/views.py
  back/friends/migrations/0001_initial.py
  front/src/page/changePassword.js
  front/src/page/editProfile.js
  front/src/utils/language.js
  front/src/vault.js
  front/styles/changePassword.css
  vault/.env
Labels: Fix

#173 [Feat/#171] 탈퇴하기 기능(프론트 에러처리, 언어 키 수정) 추가
  front/index.html
  front/src/page/editProfile.js
  front/src/utils/language.js
  front/styles/editProfile.css
  front/styles/register.css
Labels: Fix
